version: "3.8"
services:
  mysql:
    image: mysql:8.1.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./private/mysql:/var/lib/mysql
    networks:
      - webnet
    expose:
      - 3306
  web:
    image: ghcr.io/hectortav/coupons:main
    restart: always
    networks:
      - webnet
    depends_on:
      - redis
    expose:
      - 3000
  nginx:
    image: ghcr.io/hectortav/nginx:main
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - webnet
    links:
      - web
networks:
  webnet:
