FROM nginx:1.25.0-alpine
LABEL org.opencontainers.image.source=https://github.com/hectortav/coupons

RUN rm /etc/nginx/conf.d/*

COPY ./default.conf /etc/nginx/conf.d/

EXPOSE 80 443

CMD ["nginx","-g","daemon off;"] 
